package libyears.model

enum class LibyearStatus {
    NO_RESULT,
    SEM_VERSION_WITH_DEFAULT,
    SEM_VERSION_WITHOUT_DEFAULT,
    DATE_WITH_DEFAULT,
    DATE_WITHOUT_DEFAULT,
    NEWER_THAN_DEFAULT
}
