# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
       gradle-version: 8.5

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Execute tests
      run: ./gradlew test

    - name: Create dep graphs
      run: ./gradlew run --args="create-dependency-graph --projects-dir=technical-lag-benchmark/packageFiles --output-path=technical-lag-benchmark/graphs"

    - name: Calculate statistics
      run: ./gradlew run --args="calculate-technical-lag --dependency-graph-dirs=technical-lag-benchmark/graphs --output-path=technical-lag-benchmark/statistics"

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: statistics
        path: technical-lag-benchmark/statistics


    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: technical-lag-benchmark/statistics